[package]
name = "advent-of-code-2023-in-rust"
version = "0.1.0"
edition = "2021"

# Specify a default binary to run if no --bin is specified
default-run = "day_13"

[dependencies]
cached = "0.53.1"
itertools = "0.13.0"
ndarray = "0.16.1"
num = "0.4.3"
regex = "1.11.0"
